# A1 — NumPy (vectorized, no `for` loops)

Rule: every task below must be done with whole-array operations. **No Python `for` loops.**

The data you operate on is given in the next cell. Fill in each TODO yourself.

In [17]:
import numpy as np

In [18]:
# --- Given data: work on THESE (don't change them) ---

# A 2-D array (4 rows x 3 columns) for the means / threshold / normalize tasks
data = np.array([
    [12,  7, 20],
    [ 5, 18,  9],
    [25,  3, 14],
    [ 8, 11, 30],
])

# Two 1-D vectors for the dot-product task
v1 = np.array([1, 2, 3, 4])
v2 = np.array([10, 20, 30, 40])

print("data shape:", data.shape)
print(data)

data shape: (4, 3)
[[12  7 20]
 [ 5 18  9]
 [25  3 14]
 [ 8 11 30]]


## Task 1 — Row means and column means
Compute the mean of each **row** and the mean of each **column** of `data`.
<br>Hint: it's one function with an `axis=` argument. Which axis is rows, which is columns?

In [24]:
# TODO: column means (one value per column)
def compute_column_means(data):
    return np.mean(data, axis=0)
column_means = compute_column_means(data)
print('Column_means', column_means)

# TODO: row means (one value per row)
def compute_row_means(data):
    return np.mean(data, axis=1)

row_means = compute_row_means(data)
print('Row means', row_means)


Column_means [12.5   9.75 18.25]
Row means [13.         10.66666667 14.         16.33333333]


## Task 2 — Threshold-replace
Make a new array where every value in `data` **greater than 15** is replaced with `0`, and all other values are kept as-is.
<br>Hint: a boolean mask (`data > 15`) or `np.where(...)`. Don't mutate `data` — make a copy/new array.

In [20]:
# TODO: threshold-replace (values > 15 become 0)

def replace_value(data):
    new_data = np.where(data > 15, 0, data)
    return new_data

print('threshol-replace', replace_value(data))


threshol-replace [[12  7  0]
 [ 5  0  9]
 [ 0  3 14]
 [ 8 11  0]]


## Task 3 — Min-max normalize
Rescale all values of `data` so the smallest becomes 0 and the largest becomes 1.
<br>Hint: the formula is `(x - min) / (max - min)`. Think about whether you want the global min/max or per-column.

In [21]:
# TODO: min-max normalize



def normalize(data):
  normalized = (data - data.min()) / (data.max() - data.min())
  return normalized

print('normalized', normalize(data))


normalized [[0.33333333 0.14814815 0.62962963]
 [0.07407407 0.55555556 0.22222222]
 [0.81481481 0.         0.40740741]
 [0.18518519 0.2962963  1.        ]]


## Task 4 — Dot product, two ways
Compute the dot product of `v1` and `v2` using NumPy's built-in way, AND a second more manual (but still vectorized) way. Then prove they match.
<br>Hint: `np.dot` / the `@` operator for one way; element-wise multiply then sum for the other. Finish with `assert np.allclose(way1, way2)`.

In [ ]:
# TODO: dot product way 1
dot1 = np.dot(v1, v2)
print('dot1', dot1)

# TODO: dot product way 2 (vectorized, no loop)
dot2 = np.sum(v1 * v2)
print('dot2', dot2)

# TODO: assert they match

assert np.allclose(dot1, dot2)


dot1 300
dot2 300
True


## Task 5 — Explain broadcasting
In your own words (replace this text): what is broadcasting, and what is the rule for when two array shapes are allowed to combine?

**Broadcasting** is how NumPy does arithmetic on arrays that have different shapes (the same / different?) shapes,
by automatically strecthing the smaller array to match the larger one — without copying data or writing a loop.

**The rule:** line the two shapes up from the right (left / right?).
Each dimension is compatible only if the two values are equal, or if one of them is 1.

**Example:** `data * np.array([1, 2, 3])` works because data is shape (4, 3) and the vector is shape (3,),
so the vector gets stretched across all 4 rows. The result is (4, 3).